spring.application.name=bicicletario
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
equipamento.base-url=http://ec2-3-91-187-43.compute-1.amazonaws.com:8020/api
externo.base-url=http://ec2-3-91-187-43.compute-1.amazonaws.com:8060/api

