spring.application.name=bicicletario
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
equipamento.service.url=http://equipamento-microsservico-url.com/api
externo.service.url=http://externo-microsservico-url.com/api

