spring.application.name=bicicletario
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
equipamento.service.url=http://ec2-3-91-187-43.compute-1.amazonaws.com:8020/api
externo.service.url=http://externo-microsservico-url.com/api

